"""`pipeline.AnalysisResult` <-> DB rows, and the background job that runs a `Pipeline`.

This is the only place `pipeline.Pipeline` gets called from the API layer. Everything
here is additive around the existing engine — no changes to `pipeline.py` itself.
"""

from __future__ import annotations

import logging

from sqlalchemy.orm import Session, sessionmaker

from core.enums import BodyPart, Modality
from pipeline import Pipeline
from routing import ExpertRegistry, ModalityRouter

from .models import (
    Analysis,
    AnalysisFinding,
    AnalysisRecommendation,
    ExpertExecutionRecord,
    Series,
    Study,
)

logger = logging.getLogger(__name__)


def create_study(
    db: Session,
    *,
    study_id: str,
    modality: str,
    body_part: str,
    source_filename: str,
    storage_path: str,
) -> Study:
    # `study_id` is generated by the caller (api/routes/studies.py), not left to the
    # column default, because the caller needs the same ID to name the on-disk
    # directory it writes the upload into before this row exists.
    study = Study(
        id=study_id,
        modality=modality,
        body_part=body_part,
        source_filename=source_filename,
        storage_path=storage_path,
    )
    db.add(study)
    db.commit()
    db.refresh(study)
    return study


def create_queued_analysis(db: Session, *, study_id: str, series_id: str | None = None) -> Analysis:
    analysis = Analysis(study_id=study_id, series_id=series_id, status="queued")
    db.add(analysis)
    db.commit()
    db.refresh(analysis)
    return analysis


def run_analysis(session_factory: sessionmaker[Session], registry: ExpertRegistry, analysis_id: str) -> None:
    """The background job: run `Pipeline.analyze` and persist the outcome.

    Opens its own session — a `BackgroundTasks` job runs after the request that
    scheduled it has already returned, so it must not reuse a request-scoped session
    that FastAPI may have already closed.
    """
    db = session_factory()
    try:
        analysis = db.get(Analysis, analysis_id)
        if analysis is None:
            logger.error("api.persistence: analysis %s vanished before it could run", analysis_id)
            return
        study = db.get(Study, analysis.study_id)
        if study is None:
            _mark_failed(db, analysis, "study record is missing")
            return

        # A DICOM series (Series.storage_dir) takes precedence over the study's own
        # single-file storage_path — set only for one or the other, never both (see
        # api/models.py: storage_path is null for source="orthanc" studies, series_id
        # is null for plain-upload analyses).
        series: Series | None = None
        if analysis.series_id is not None:
            series = db.get(Series, analysis.series_id)
            if series is None:
                _mark_failed(db, analysis, "series record is missing")
                return

        path = series.storage_dir if series is not None else study.storage_path
        modality_value = series.modality if series is not None else study.modality
        body_part_value = series.body_part if series is not None else study.body_part
        if path is None:
            _mark_failed(db, analysis, "study/series has no analyzable storage path")
            return

        analysis.status = "running"
        db.commit()

        try:
            pipe = Pipeline(ModalityRouter(registry))
            result = pipe.analyze(
                path,
                modality=Modality(modality_value),
                body_part=BodyPart(body_part_value),
            )
        except Exception as exc:  # noqa: BLE001 — the whole analysis failed, not one expert
            _mark_failed(db, analysis, f"{type(exc).__name__}: {exc}")
            return

        analysis.status = "complete"
        analysis.pipeline_analysis_id = result.analysis_id
        analysis.report_text = result.report.to_text() if result.report else None
        analysis.verification_ok = result.verification.ok if result.verification else None
        analysis.triage_urgency = result.triage_urgency.name

        for finding in result.findings:
            db.add(
                AnalysisFinding(
                    analysis_id=analysis.id,
                    label=finding.label,
                    canonical_label=finding.canonical_label,
                    probability=finding.probability,
                    present=finding.present,
                    confidence=finding.confidence,
                    laterality=finding.laterality,
                    location=finding.location,
                    size_mm=finding.size_mm,
                    volume_ml=finding.volume_ml,
                    count=finding.count,
                    source=finding.source,
                    execution_id=finding.execution_id,
                )
            )
        for recommendation in result.recommendations:
            db.add(
                AnalysisRecommendation(
                    analysis_id=analysis.id,
                    label=recommendation.label,
                    text=recommendation.text,
                    urgency=recommendation.urgency.name,
                )
            )
        for execution in result.expert_executions:
            db.add(
                ExpertExecutionRecord(
                    analysis_id=analysis.id,
                    execution_id=execution.execution_id,
                    expert=execution.expert,
                    status=execution.status,
                    expert_version=execution.expert_version,
                    preprocessing_version=execution.preprocessing_version,
                    error=execution.error,
                )
            )
        db.commit()
    finally:
        db.close()


def _mark_failed(db: Session, analysis: Analysis, error: str) -> None:
    analysis.status = "failed"
    analysis.error = error
    db.commit()
    logger.warning("api.persistence: analysis %s failed: %s", analysis.id, error)
