"""`pipeline.AnalysisResult` <-> DB rows, and the background job that runs a `Pipeline`.

This is the only place `pipeline.Pipeline` gets called from the API layer. Everything
here is additive around the existing engine — no changes to `pipeline.py` itself.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pydicom
from sqlalchemy import select
from sqlalchemy.orm import Session, sessionmaker

from core.enums import BodyPart, Modality
from core.types import Scan, ScanMetadata
from experts.mri_brats import BUNDLE_MODALITY_ORDER, canonical_sequence_name
from pipeline import Pipeline
from routing import ExpertRegistry, ModalityRouter

from .models import (
    Analysis,
    AnalysisFinding,
    AnalysisRecommendation,
    ExpertExecutionRecord,
    Series,
    Study,
)

logger = logging.getLogger(__name__)


def create_study(
    db: Session,
    *,
    study_id: str,
    modality: str,
    body_part: str,
    source_filename: str,
    storage_path: str,
) -> Study:
    # `study_id` is generated by the caller (api/routes/studies.py), not left to the
    # column default, because the caller needs the same ID to name the on-disk
    # directory it writes the upload into before this row exists.
    study = Study(
        id=study_id,
        modality=modality,
        body_part=body_part,
        source_filename=source_filename,
        storage_path=storage_path,
    )
    db.add(study)
    db.commit()
    db.refresh(study)
    return study


def create_queued_analysis(db: Session, *, study_id: str, series_id: str | None = None) -> Analysis:
    analysis = Analysis(study_id=study_id, series_id=series_id, status="queued")
    db.add(analysis)
    db.commit()
    db.refresh(analysis)
    return analysis


def _representative_dicom_file(storage_dir: str) -> Path | None:
    """The first file in a series directory, standing in for the whole series --
    `SeriesDescription` (like `ViewPosition`/`BodyPartExamined` in dicom_ingest.py's
    `_read_instance_header`) is expected constant across a series' instances."""
    directory = Path(storage_dir)
    if not directory.is_dir():
        return None
    for candidate in sorted(directory.iterdir()):
        if candidate.is_file():
            return candidate
    return None


def _series_description(storage_dir: str) -> str | None:
    """Read the DICOM SeriesDescription tag from one representative file in a series
    directory -- the only place a sequence's clinical name (T1c/T1/T2/FLAIR, or a
    scout/localizer that isn't part of the 4-sequence BraTS protocol) is recorded.
    `Series` (api/models.py) has no dedicated column for it: deriving it here, read-time,
    from a file already downloaded to disk is just as correct as capturing it at ingest
    and needs no migration -- unlike `Series.modality`/`body_part`, which ARE captured at
    ingest because that mapping is a lookup table over the DICOM Modality/BodyPartExamined
    tags needed for *every* series (routing depends on it), not a single string comparison
    used only when grouping one modality's multi-sequence studies.
    """
    representative = _representative_dicom_file(storage_dir)
    if representative is None:
        return None
    dataset = pydicom.dcmread(str(representative), stop_before_pixels=True)
    return getattr(dataset, "SeriesDescription", None) or None


def _match_brats_sequences(db: Session, study_id: str) -> dict[str, str] | None:
    """Group a study's `Series` rows into the four co-registered sequences
    `brats_mri_segmentation` needs (t1c/t1/t2/flair), or return None if not all four
    are present -- the caller falls back to the study's ordinary single-path analysis
    (which fails closed with "no analyzable storage path" for a multi-series study that
    has no single-file `storage_path`, same as before this function existed).

    Matches on each `Series`' own modality/body_part rather than the parent `Study`'s:
    a DICOM study imported from Orthanc always stamps `Study.modality`/`body_part`
    UNKNOWN by design (a study can span several modalities/body parts -- see
    api/dicom_ingest.py's own docstring on `import_study_from_orthanc`), so only the
    per-series values (resolved once at ingest, see `Series.modality` in api/models.py)
    are trustworthy here.

    A brain MRI study legitimately contains series outside the 4-sequence protocol
    (scouts, localizers, post-processing series) -- `canonical_sequence_name` raising on
    those is expected and they're skipped, not treated as an error for the whole study.
    """
    candidates = (
        db.execute(
            select(Series).where(
                Series.study_id == study_id,
                Series.modality == Modality.MRI.value,
                Series.body_part == BodyPart.BRAIN.value,
            )
        )
        .scalars()
        .all()
    )

    sequence_paths: dict[str, str] = {}
    for series in candidates:
        description = _series_description(series.storage_dir)
        if not description:
            logger.info(
                "api.persistence: series %s has no SeriesDescription; skipped for "
                "BraTS sequence matching",
                series.id,
            )
            continue
        try:
            canonical = canonical_sequence_name(description)
        except ValueError:
            logger.info(
                "api.persistence: series %s SeriesDescription %r is not a recognised "
                "BraTS sequence name; skipped",
                series.id,
                description,
            )
            continue
        if canonical in sequence_paths:
            logger.warning(
                "api.persistence: study %s has more than one series matching BraTS "
                "sequence %r; keeping the first (series %s)",
                study_id,
                canonical,
                sequence_paths[canonical],
            )
            continue
        sequence_paths[canonical] = series.storage_dir

    missing = [name for name in BUNDLE_MODALITY_ORDER if name not in sequence_paths]
    if missing:
        if sequence_paths:
            logger.info(
                "api.persistence: study %s has %d/%d BraTS sequences (missing %s); "
                "not enough to run mri_brats",
                study_id,
                len(sequence_paths),
                len(BUNDLE_MODALITY_ORDER),
                missing,
            )
        return None
    return sequence_paths


def _build_brats_scan(study: Study, sequence_paths: dict[str, str]) -> Scan:
    """A `Scan` for the multi-sequence BraTS path -- built directly rather than via
    `ingest.loaders.load_scan` (which only ever reads one path into `Scan.data`).

    `data` is a placeholder, deliberately: `BraTSExpert.predict()` reads exclusively
    from `scan.meta.extra["sequence_paths"]` on disk (it needs four separate
    co-registered volumes; one `Scan.data` tensor can't hold four, so there IS no single
    real pixel array to put here), and its `findings_from_prediction` hook never touches
    `scan.data` either. Confirmed nothing upstream of the expert needs it to be real
    either: `ModalityRouter.route` (routing/router.py) keys purely on `scan.meta`, and
    `Reporter.report`/`Verifier.verify` take `Finding`s and `scan.meta`, never `scan`
    itself -- grepped reporting/*.py for `.data` and found no reference.
    """
    import torch

    meta = ScanMetadata(
        modality=Modality.MRI,
        body_part=BodyPart.BRAIN,
        source_path=study.storage_path,
        extra={"sequence_paths": sequence_paths},
    )
    return Scan(data=torch.zeros((1, 1, 1, 1)), meta=meta)


def run_analysis(session_factory: sessionmaker[Session], registry: ExpertRegistry, analysis_id: str) -> None:
    """The background job: run `Pipeline.analyze` and persist the outcome.

    Opens its own session — a `BackgroundTasks` job runs after the request that
    scheduled it has already returned, so it must not reuse a request-scoped session
    that FastAPI may have already closed.
    """
    db = session_factory()
    try:
        analysis = db.get(Analysis, analysis_id)
        if analysis is None:
            logger.error("api.persistence: analysis %s vanished before it could run", analysis_id)
            return
        study = db.get(Study, analysis.study_id)
        if study is None:
            _mark_failed(db, analysis, "study record is missing")
            return

        # A DICOM series (Series.storage_dir) takes precedence over the study's own
        # single-file storage_path — set only for one or the other, never both (see
        # api/models.py: storage_path is null for source="orthanc" studies, series_id
        # is null for plain-upload analyses).
        series: Series | None = None
        if analysis.series_id is not None:
            series = db.get(Series, analysis.series_id)
            if series is None:
                _mark_failed(db, analysis, "series record is missing")
                return

        path = series.storage_dir if series is not None else study.storage_path
        modality_value = series.modality if series is not None else study.modality
        body_part_value = series.body_part if series is not None else study.body_part

        # A study-level submission (series is None) whose study has no single-file
        # storage_path is a multi-series study -- currently always an Orthanc import
        # (see api/models.py: storage_path is null exactly when source="orthanc"). That
        # is the only shape that can supply BraTS's four co-registered MRI sequences, so
        # it's the only case worth trying to group. Gating on the *study's* modality/
        # body_part instead (mirroring the single-series branch below) would make this
        # unreachable: Study.modality/body_part are always UNKNOWN for such studies by
        # design (api/dicom_ingest.py) -- so this looks at each Series' own (reliable)
        # modality/body_part via `_match_brats_sequences` instead.
        brats_scan: Scan | None = None
        if series is None and study.storage_path is None:
            sequence_paths = _match_brats_sequences(db, study.id)
            if sequence_paths is not None:
                brats_scan = _build_brats_scan(study, sequence_paths)

        if path is None and brats_scan is None:
            _mark_failed(db, analysis, "study/series has no analyzable storage path")
            return

        analysis.status = "running"
        db.commit()

        try:
            pipe = Pipeline(ModalityRouter(registry))
            if brats_scan is not None:
                result = pipe.analyze_scan(brats_scan)
            else:
                result = pipe.analyze(
                    path,
                    modality=Modality(modality_value),
                    body_part=BodyPart(body_part_value),
                )
        except Exception as exc:  # noqa: BLE001 — the whole analysis failed, not one expert
            _mark_failed(db, analysis, f"{type(exc).__name__}: {exc}")
            return

        analysis.status = "complete"
        analysis.pipeline_analysis_id = result.analysis_id
        analysis.report_text = result.report.to_text() if result.report else None
        analysis.verification_ok = result.verification.ok if result.verification else None
        analysis.triage_urgency = result.triage_urgency.name

        for finding in result.findings:
            db.add(
                AnalysisFinding(
                    analysis_id=analysis.id,
                    label=finding.label,
                    canonical_label=finding.canonical_label,
                    probability=finding.probability,
                    present=finding.present,
                    confidence=finding.confidence,
                    laterality=finding.laterality,
                    location=finding.location,
                    size_mm=finding.size_mm,
                    volume_ml=finding.volume_ml,
                    count=finding.count,
                    source=finding.source,
                    execution_id=finding.execution_id,
                )
            )
        for recommendation in result.recommendations:
            db.add(
                AnalysisRecommendation(
                    analysis_id=analysis.id,
                    label=recommendation.label,
                    text=recommendation.text,
                    urgency=recommendation.urgency.name,
                )
            )
        for execution in result.expert_executions:
            db.add(
                ExpertExecutionRecord(
                    analysis_id=analysis.id,
                    execution_id=execution.execution_id,
                    expert=execution.expert,
                    status=execution.status,
                    expert_version=execution.expert_version,
                    preprocessing_version=execution.preprocessing_version,
                    error=execution.error,
                )
            )
        db.commit()
    finally:
        db.close()


def _mark_failed(db: Session, analysis: Analysis, error: str) -> None:
    analysis.status = "failed"
    analysis.error = error
    db.commit()
    logger.warning("api.persistence: analysis %s failed: %s", analysis.id, error)
